// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/gorilla/mux"
	"github.com/oapi-codegen/runtime"
	ccfg "github.com/rkosegi/go-http-commons/config"
)

// Defines values for DeviceProtocol.
const (
	Tuya31 DeviceProtocol = "tuya3.1"
	Tuya34 DeviceProtocol = "tuya3.4"
)

// Valid indicates whether the value is a known member of the DeviceProtocol enum.
func (e DeviceProtocol) Valid() bool {
	switch e {
	case Tuya31:
		return true
	case Tuya34:
		return true
	default:
		return false
	}
}

// AppConfig Root configuration object
type AppConfig struct {
	// Devices Map of devices
	Devices DeviceMap `json:"devices"`

	// Server Server configuration
	Server *ccfg.ServerConfig `json:"server,omitempty"`
}

// DeviceList List of devices, sorted by name
type DeviceList = []DeviceSpec

// DeviceMap Map of devices
type DeviceMap map[string]DeviceSpec

// DeviceProtocol Protocol version to use when speaking to device
type DeviceProtocol string

// DeviceSpec defines model for DeviceSpec.
type DeviceSpec struct {
	// Address Device network address.
	// Might include port, but if not specified then 6668 is assumed.
	Address string `json:"address"`

	// ConnectTimeout Connection timeout.
	// Default value is 10s
	ConnectTimeout time.Duration `json:"connectTimeout"`

	// Id Device ID from Tuya API
	Id string `json:"id"`

	// Key Encryption key from Tuya API
	Key string `json:"key"`

	// Name Device symbolic name. Must be unique
	Name string `json:"name"`

	// Protocol Protocol version to use when speaking to device
	Protocol DeviceProtocol `json:"protocol"`

	// ReadTimeout Network read timeout.
	// Default value is 10s
	ReadTimeout time.Duration `json:"readTimeout"`

	// WriteTimeout Network write timeout.
	// Default value is 10s
	WriteTimeout time.Duration `json:"writeTimeout"`
}

// Device defines model for device.
type Device = string

// SendCommandRequest defines model for SendCommandRequest.
type SendCommandRequest struct {
	// DefaultRequest When true, then default request fields are added to payload (`gwId`, `devId` and `t`)
	DefaultRequest *bool `json:"defaultRequest,omitempty"`

	// Payload Payload to send to the device. Only considered when `defaultRequest` is false (or not specified at all)
	Payload *map[string]interface{} `json:"payload,omitempty"`
}

// SendCommandJSONBody defines parameters for SendCommand.
type SendCommandJSONBody struct {
	// DefaultRequest When true, then default request fields are added to payload (`gwId`, `devId` and `t`)
	DefaultRequest *bool `json:"defaultRequest,omitempty"`

	// Payload Payload to send to the device. Only considered when `defaultRequest` is false (or not specified at all)
	Payload *map[string]interface{} `json:"payload,omitempty"`
}

// CreateDeviceJSONRequestBody defines body for CreateDevice for application/json ContentType.
type CreateDeviceJSONRequestBody = DeviceSpec

// SendCommandJSONRequestBody defines body for SendCommand for application/json ContentType.
type SendCommandJSONRequestBody SendCommandJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListDevices List all configured devices
	// (GET /device)
	ListDevices(w http.ResponseWriter, r *http.Request)
	// CreateDevice Create a new device
	// (POST /device)
	CreateDevice(w http.ResponseWriter, r *http.Request)
	// DeleteDevice Delete a device
	// (DELETE /device/{device})
	DeleteDevice(w http.ResponseWriter, r *http.Request, device Device)
	// GetDevice Get device detail
	// (GET /device/{device})
	GetDevice(w http.ResponseWriter, r *http.Request, device Device)
	// SendCommand Send a command to the device
	// (POST /device/{device}/command/{command})
	SendCommand(w http.ResponseWriter, r *http.Request, device Device, command int)
	// GetDeviceStats Get device statistics
	// (GET /device/{device}/stats)
	GetDeviceStats(w http.ResponseWriter, r *http.Request, device Device)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListDevices operation middleware
func (siw *ServerInterfaceWrapper) ListDevices(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListDevices(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateDevice operation middleware
func (siw *ServerInterfaceWrapper) CreateDevice(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateDevice(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteDevice operation middleware
func (siw *ServerInterfaceWrapper) DeleteDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "device" -------------
	var device Device

	err = runtime.BindStyledParameterWithOptions("simple", "device", mux.Vars(r)["device"], &device, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteDevice(w, r, device)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDevice operation middleware
func (siw *ServerInterfaceWrapper) GetDevice(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "device" -------------
	var device Device

	err = runtime.BindStyledParameterWithOptions("simple", "device", mux.Vars(r)["device"], &device, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDevice(w, r, device)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SendCommand operation middleware
func (siw *ServerInterfaceWrapper) SendCommand(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "device" -------------
	var device Device

	err = runtime.BindStyledParameterWithOptions("simple", "device", mux.Vars(r)["device"], &device, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device", Err: err})
		return
	}

	// ------------- Path parameter "command" -------------
	var command int

	err = runtime.BindStyledParameterWithOptions("simple", "command", mux.Vars(r)["command"], &command, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "command", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SendCommand(w, r, device, command)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetDeviceStats operation middleware
func (siw *ServerInterfaceWrapper) GetDeviceStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "device" -------------
	var device Device

	err = runtime.BindStyledParameterWithOptions("simple", "device", mux.Vars(r)["device"], &device, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "device", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetDeviceStats(w, r, device)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{})
}

type GorillaServerOptions struct {
	BaseURL          string
	BaseRouter       *mux.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r *mux.Router) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r *mux.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, GorillaServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options GorillaServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = mux.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.HandleFunc(options.BaseURL+"/device", wrapper.ListDevices).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/device", wrapper.CreateDevice).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/device/{device}", wrapper.DeleteDevice).Methods(http.MethodDelete)

	r.HandleFunc(options.BaseURL+"/device/{device}", wrapper.GetDevice).Methods(http.MethodGet)

	r.HandleFunc(options.BaseURL+"/device/{device}/command/{command}", wrapper.SendCommand).Methods(http.MethodPost)

	r.HandleFunc(options.BaseURL+"/device/{device}/stats", wrapper.GetDeviceStats).Methods(http.MethodGet)

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"tFjdbtu4En6VAc+56AEUyUlzil3fdeOga6DpBk2AvWgDmBZHEhuKVEnKrmDo3RckJcey5E1atFeR+TM/",
	"33wznMmOpKqslERpDZnvSEU1LdGi9r8YbniK4cukmleWK0nmZOHXQdISSUS4W6qoLUhE/NK8vxgRjV9r",
	"rpGRudU1RsSkBZbUSbRN5U4aq7nMSdu24TAa+4diHL3+O5TsSpUllexj2HOrqZIWpf+kVSV4Sp1ZyRfj",
	"bNsdqKi0qlDbThjDjNbCHggaOvV3gRK8lWDdZ3ceOqsg4yiYAaoRKGPIwCqoaCMUZfBqlW+XbBXBiuFm",
	"yVZAJYOVXf2PRL2ja6UEUknaiHS3xibcduKsAoPS/7UFQkAzhr+kaCBV0nCGGhlsnZmroV8r4AYyKgzC",
	"K6VBKgumwpRnHBlQC1SIA6PU+gum1qHf4/8ULLcSsPTwva2qKyUzno/N/qiUdXZlPK+1DwZ0gqNRDJwn",
	"/vO/GjMyJ/9JngiYdOqSwK8bWjm0DOoN6rHWO78+1DvyLCLfznJ11i2maZbH4V7ny8H+GS8rpT0xOha7",
	"484FR+05ybkt6nWcqjLRj8pgzpNcnRXWVmepKkslTRJsIUdgftq7/dBGXe6851MUdKugsi7gJgKjtEUG",
	"62afaxbLF8J3V2Hq8Ot8p1rThuwNcOC6BGKMO+VU3A4C9XLxQw9uaHXgwJhovfpbraxKlZjIgW4HNqiN",
	"o5JVUBsMZDcV0kcuc7e4rzEo69KhbOuGvo7PnVL/dUkeouMy0+v31p/03+fPMXcpYxqNOV0N0W6VfoTu",
	"XPxZ3vC8sMBlKmqG4MgVwbq2wLOjvPT15s2bN7+55KXG1CWymEwYnyopMbX3vERVTxDoKux72MKZ+LNc",
	"dIVsQ0WNTsP5zIyEDxPFXY4XfVK1EeHspN/LBWRalXBfNxTe3i6n7H7EZnz/Wqa68T/gEZvnhYSsPGGF",
	"acq1Ejz1iRLDTW0srBFqyb/WOCWtOmDg82zf89VnNmUnI/ChY4E79JNjsNXc4rOK/amfqvmomPWViJEQ",
	"1wMoo32SjKg6hO3ImQdfMbnM1NivpbSoaWphy20R+GFKqm1fY6A2riB8vL67d8RxaSN4itLgQSV/W9G0",
	"QLiIZyQitRZkTlzhNvMk2W63MfXbsdJ50t01yfvl1fWHu+uzi3gWF7b0kbfcCifOW9Hrt2qvHNaas9yh",
	"0xUvMieb83gWz9xtVaGkFSdz8jqexa+7l8UXlOSp08pxIrjv0ALjPrGpblyFpULsnz5kBwXXlSwfuCXr",
	"XpTFfk+jqZTzzmm4mM2+q5t64YPdnnoTTljs24y6LKlu+hfw1MmIVMpMV71wFihI3D69DEMsrjRSi4vD",
	"1jR0m81PxiE8jV0XMED8/BdpiqaL4paaAyAdgJez30+WUJ9gOd+g9EUUqHAp2wB+48YeByqAOQTcneiY",
	"nOzC3zZoE2g9uYcBWfj1g4AMsLo8aajGUm2cPwOLgjSge2uiPpeGWt+hPaVydlIlQ0u5CAhevhhBh797",
	"6TNVy2NzfUofCz8cvz5NE+DpSF802ocJ3N0VNzclu+7DR6LPnyEiB2MW+VEbonFSeoGwXEyPiOle4bMz",
	"IpcWc9SkbR9GaTtl3mCOTCaGyPYlke8d8JOYqdMUjclqIZrAgtnUU7WhgrN+YjwKuLMDKHR+D2e7ydRJ",
	"jKVhKv93Ht/5Y99BZieXG8tT84sIPVTwo6Tez37hXni2d32z0c6TZFcoY9v5zrXWbUIrnmxc+7+hmtO1",
	"CEAU+yfD90FkToRKqfDLx2XzT2Ws91Nl/jkP6uPw8ugjMRcXs9n/RyJulbagJGwLnhYHQlznJbixKLnM",
	"4+MG9Emqa0tGQu8LhP44ZEoD9Wz0g1CBoe1pfXZYmge0ThROQd08uSeSGf3LZpzIS5kpXdIwJU1e9Y1b",
	"+9D+EwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
